basePath: /api/v1
definitions:
  api.AuthReq:
    properties:
      nick:
        type: string
      password:
        type: string
    type: object
  api.AuthRes:
    properties:
      createdAt:
        type: integer
      email:
        type: string
      id:
        type: string
      lastIP:
        type: string
      lastTime:
        type: integer
      nick:
        type: string
      role:
        type: integer
      state:
        type: integer
      token:
        type: string
      updatedAt:
        type: integer
    type: object
host: 127.0.0.1:10001
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /api/v1/auth:
    post:
      consumes:
      - application/json
      parameters:
      - description: 登录参数
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/api.AuthReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.AuthRes'
      summary: 登录接口
      tags:
      - 用户接口
swagger: "2.0"
