// Package cdnAdmin GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package cdnAdmin

import "github.com/swaggo/swag"

const docTemplatecdnAdmin = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/testapi/get-string-by-int/{some_id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "登录接口",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AuthReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.AuthRes"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AuthReq": {
            "type": "object",
            "properties": {
                "nick": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "api.AuthRes": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastIP": {
                    "type": "string"
                },
                "lastTime": {
                    "type": "integer"
                },
                "nick": {
                    "type": "string"
                },
                "role": {
                    "type": "integer"
                },
                "state": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfocdnAdmin holds exported Swagger Info so clients can modify it
var SwaggerInfocdnAdmin = &swag.Spec{
	Version:          "1.0",
	Host:             "petstore.swagger.io:8080",
	BasePath:         "/v2",
	Schemes:          []string{},
	Title:            "cdnAdmin的swagger文档",
	Description:      "This is a sample server Petstore server.",
	InfoInstanceName: "cdnAdmin",
	SwaggerTemplate:  docTemplatecdnAdmin,
}

func init() {
	swag.Register(SwaggerInfocdnAdmin.InstanceName(), SwaggerInfocdnAdmin)
}
