// Package cdnAdmin GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package cdnAdmin

import "github.com/swaggo/swag"

const docTemplateCdnAdmin = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/auth": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户接口"
                ],
                "summary": "登录接口",
                "parameters": [
                    {
                        "description": "登录参数",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AuthReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.AuthRes"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AuthReq": {
            "type": "object",
            "properties": {
                "nick": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        },
        "api.AuthRes": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "lastIP": {
                    "type": "string"
                },
                "lastTime": {
                    "type": "integer"
                },
                "nick": {
                    "type": "string"
                },
                "role": {
                    "type": "integer"
                },
                "state": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfoCdnAdmin holds exported Swagger Info so clients can modify it
var SwaggerInfoCdnAdmin = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:10001",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Swagger Example API",
	Description:      "This is a sample server Petstore server.",
	InfoInstanceName: "CdnAdmin",
	SwaggerTemplate:  docTemplateCdnAdmin,
}

func init() {
	swag.Register(SwaggerInfoCdnAdmin.InstanceName(), SwaggerInfoCdnAdmin)
}
