// Package cdnUser GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package cdnUser

import "github.com/swaggo/swag"

const docTemplateCdnUser = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {}
}`

// SwaggerInfoCdnUser holds exported Swagger Info so clients can modify it
var SwaggerInfoCdnUser = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "CdnUser",
	SwaggerTemplate:  docTemplateCdnUser,
}

func init() {
	swag.Register(SwaggerInfoCdnUser.InstanceName(), SwaggerInfoCdnUser)
}
